# Generated by Django 2.2.7 on 2020-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_auto_20200210_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
