# Generated by Django 2.2.7 on 2020-02-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_game_is_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_bought',
            field=models.BooleanField(default=True),
        ),
    ]
