# Generated by Django 2.2.7 on 2020-02-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0006_auto_20200210_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
