# Generated by Django 2.2.7 on 2020-02-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0008_auto_20200210_1635'),
        ('gamestore', '0007_auto_20200210_1439'),
    ]

    operations = [
    ]
