# Generated by Django 2.2.7 on 2020-02-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0010_auto_20200211_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='player_items',
            new_name='gameState',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='score',
        ),
    ]
