# Generated by Django 2.2.7 on 2020-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0011_auto_20200211_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='gameState',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highscore',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_items',
            field=models.ManyToManyField(to='gamestore.Item'),
        ),
    ]
