# Generated by Django 2.2.7 on 2020-02-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0012_auto_20200211_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='player_items',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='score',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='gameState',
            field=models.TextField(default={'score': 0}, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
