# Generated by Django 2.2.7 on 2020-02-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0013_auto_20200212_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_bought',
        ),
    ]
